# Generated by Django 3.0.4 on 2020-06-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.CharField(max_length=200, null=True)),
                ('n2', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
